name: 'Cleanup untagged container images'
description: 'Delete untagged container images on ghcr.io for a given user and container name.'
author: mitchfen
branding:
  icon: trash
  color: orange
inputs:
  username:
    description: 'Username of container owner.'
    required: true
  container-name:
    description: 'Name of container to delete untagged images for.'
    required: true
  token:
    description: 'Token with package read and delete permission.'
    required: true
runs:
  using: "composite"
  steps:
    - run: python ${{ github.action_path }}/cleanupUntaggedImages.py
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        CONTAINER_NAME: ${{ inputs.container-name }}
        USERNAME: ${{ inputs.username }}
